create table phones
(
    id           bigint generated by default as identity,
    city_code    integer not null,
    country_code varchar(255),
    number       bigint  not null,
    user_id      varchar(255),
    primary key (id)
);

create table users
(
    id           varchar(255) not null,
    active       boolean      not null,
    date_created timestamp(6),
    email        varchar(255) not null,
    last_login   timestamp(6),
    name         varchar(255),
    password     varchar(60)  not null,
    role         varchar(255),
    primary key (id)
);
alter table if exists users add constraint AR_igio4jgigdgd9gklaafwk4kks unique (email);
alter table if exists phones add constraint UK_iyb1ctsfd11m9cbkngt35br2v unique (number);
alter table if exists phones add constraint FKmg6d77tgqfen7n1g763nvsqe3 foreign key (user_id) references users;


